# Generated by Django 5.1.3 on 2024-11-27 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('admission_date', models.DateField(null=True, verbose_name='Admission Date')),
                ('emergency_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Emergency Contact Email')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Phone')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this resident is currently active in the care home.', verbose_name='Active')),
                ('care_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='homes.carehome', verbose_name='Care Home')),
            ],
            options={
                'verbose_name': 'Resident',
                'verbose_name_plural': 'Residents',
            },
        ),
    ]
