# Generated by Django 5.0.6 on 2024-06-30 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_carehome_capacity_carehome_manager'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='admission_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='care_home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='homes.carehome'),
        ),
    ]
