# Generated by Django 5.0.6 on 2024-06-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_resident_admission_date_resident_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='resident',
            name='emergency_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Emergency Contact Email'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Phone'),
        ),
    ]
