# Generated by Django 5.0.6 on 2024-07-08 19:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0004_visithistory'),
        ('services', '0011_alter_service_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentServiceFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_frequencies', to='residents.resident')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
            options={
                'unique_together': {('resident', 'service_type')},
            },
        ),
        migrations.DeleteModel(
            name='VisitHistory',
        ),
    ]
