# Generated by Django 5.0.6 on 2024-07-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0005_residentservicefrequency_delete_visithistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResidentServiceFrequency',
        ),
    ]
