# Generated by Django 5.0.6 on 2024-06-30 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='recurrence_pattern',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Expected duration of the service'),
        ),
    ]
