# Generated by Django 5.0.6 on 2024-06-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_last_refusal_date_service_refusal_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockedtime',
            name='resident',
        ),
    ]
