# Generated by Django 5.0.6 on 2024-06-30 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_caregiver_alter_service_resident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation',
            name='escalation_type',
            field=models.CharField(choices=[('refusal', 'Service Refusal'), ('missed', 'Missed Service')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_escalations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='incomplete_reason',
            field=models.CharField(blank=True, choices=[('resident_unavailable', 'Resident Unavailable'), ('staff_unavailable', 'Staff Unavailable'), ('equipment_issue', 'Equipment Issue'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_chargeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='refusal_reason',
            field=models.CharField(blank=True, choices=[('resident_declined', 'Resident Declined'), ('medical_condition', 'Medical Condition'), ('family_request', 'Family Request'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='rescheduled_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_service', to='services.service'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='is_companion_service',
            field=models.BooleanField(default=False),
        ),
    ]
