# Generated by Django 5.0.6 on 2024-07-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_escalation_escalation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='incomplete_reason',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_chargeable',
        ),
        migrations.RemoveField(
            model_name='service',
            name='refusal_reason',
        ),
        migrations.RemoveField(
            model_name='service',
            name='rescheduled_service',
        ),
        migrations.AddField(
            model_name='service',
            name='completion_reason',
            field=models.CharField(blank=True, choices=[('completed', 'Service Completed'), ('refused', 'Refused Service'), ('family_visit_no_notice', 'Family Visit (No Notice)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='reschedule_reason',
            field=models.CharField(blank=True, choices=[('hospital', 'Hospital'), ('illness', 'Illness'), ('isolation', 'Isolation'), ('approved_family_visit', 'Approved Family Visit')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='refusal_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
