# Generated by Django 5.0.6 on 2024-07-01 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_service_incomplete_reason_and_more'),
    ]

    operations = [
    ]
