# Generated by Django 5.0.6 on 2024-07-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_create_initial_service_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='service',
            name='recurrence_pattern',
        ),
        migrations.AddField(
            model_name='service',
            name='recurrence',
            field=models.CharField(choices=[('once', 'Just once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually'), ('weekdays', 'Every weekday (Monday to Friday)')], default='once', max_length=20),
        ),
    ]
