# Generated by Django 5.0.6 on 2024-07-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_service_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='recurrence',
            field=models.CharField(choices=[('once', 'Just once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('weekdays', 'Every weekday (Monday to Friday)')], default='once', max_length=20),
        ),
    ]
