# Generated by Django 5.0.6 on 2024-07-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_delete_residentservicefrequency'),
        ('services', '0012_remove_service_recurrence_residentservicefrequency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='residentservicefrequency',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='residentservicefrequency',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='residentservicefrequency',
            unique_together={('resident', 'service_type', 'day_of_week')},
        ),
    ]
