# Generated by Django 5.0.6 on 2024-07-09 01:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_residentservicefrequency_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentservicefrequency',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='residentservicefrequency',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
