# Generated by Django 5.0.6 on 2024-07-09 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_residentservicefrequency_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentservicefrequency',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='residentservicefrequency',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
