# Generated by Django 5.0.6 on 2024-07-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_delete_residentservicefrequency'),
        ('services', '0016_alter_residentservicefrequency_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='residentservicefrequency',
            unique_together={('resident', 'service_type', 'start_date')},
        ),
    ]
