# Generated by Django 5.0.6 on 2024-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_alter_residentservicefrequency_repeat_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentservicefrequency',
            name='repeat_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
