# Generated by Django 5.0.6 on 2024-07-18 07:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_alter_residentservicefrequency_repeat_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentservicefrequency',
            name='repeat_every',
        ),
        migrations.RemoveField(
            model_name='residentservicefrequency',
            name='repeat_on',
        ),
        migrations.RemoveField(
            model_name='residentservicefrequency',
            name='repeat_period',
        ),
        migrations.AddField(
            model_name='residentservicefrequency',
            name='frequency',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='residentservicefrequency',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='residentservicefrequency',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residentservicefrequency',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
