# Generated by Django 5.0.6 on 2024-07-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_rename_week_day_residentservicefrequency_weekday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentservicefrequency',
            name='weekday',
        ),
        migrations.AlterField(
            model_name='residentservicefrequency',
            name='period',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, null=True),
        ),
    ]
