# Generated by Django 5.0.6 on 2024-07-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0006_delete_residentservicefrequency'),
        ('services', '0025_remove_residentservicefrequency_weekday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnscheduledService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.residentservicefrequency')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.resident')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
        ),
    ]
