# Generated by Django 5.0.6 on 2024-07-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_delete_unscheduledservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentservicefrequency',
            name='preferred_days',
            field=models.CharField(default='[]', max_length=100),
        ),
    ]
