# Generated by Django 5.0.6 on 2024-07-31 04:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_residentservicefrequency_preferred_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentservicefrequency',
            name='period',
        ),
        migrations.AddField(
            model_name='residentservicefrequency',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='residentservicefrequency',
            name='recurrence_pattern',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='residentservicefrequency',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blockedtime',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='residentservicefrequency',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residentservicefrequency',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
