# Generated by Django 5.0.6 on 2024-07-31 14:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_remove_residentservicefrequency_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='frequency_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residentservicefrequency',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
