# Generated by Django 5.0.6 on 2024-07-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_service_frequency_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentservicefrequency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
