# Generated by Django 5.0.6 on 2024-07-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_alter_residentservicefrequency_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentservicefrequency',
            name='occurrences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentservicefrequency',
            name='recurrence_end',
            field=models.CharField(choices=[('never', 'Never'), ('after', 'After'), ('on_date', 'On Date')], default='never', max_length=10),
        ),
    ]
