# Generated by Django 5.0.6 on 2024-08-12 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homes", "0004_carehome_is_active"),
        ("services", "0034_residentservicefrequency_occurrences_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blockedtime",
            name="caregivers",
            field=models.ManyToManyField(
                blank=True, related_name="blocked_times", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="blockedtime",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="blockedtime",
            name="locations",
            field=models.ManyToManyField(
                blank=True, related_name="blocked_times", to="homes.carehome"
            ),
        ),
        migrations.AddField(
            model_name="blockedtime",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="blockedtime",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="blockedtime",
            name="start_time",
            field=models.TimeField(null=True),
        ),
    ]
