# Generated by Django 5.0.6 on 2024-08-28 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0035_blockedtime_caregivers_blockedtime_end_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="residentservicefrequency",
            name="caregiver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_frequencies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
