# Generated by Django 5.0.6 on 2024-10-31 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_residentservicefrequency_caregiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='due_date',
        ),
    ]
