# Generated by Django 5.1.3 on 2024-11-27 21:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the care home', max_length=100, unique=True, verbose_name='Name')),
                ('address', models.TextField(help_text='The full address of the care home', verbose_name='Address')),
                ('phone', models.CharField(help_text='Contact phone number for the care home', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone')),
                ('capacity', models.PositiveIntegerField(default=100, help_text='Maximum number of residents the care home can accommodate', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Capacity')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the care home was added to the system', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the care home information was last updated', verbose_name='Updated At')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this care home is active.', verbose_name='Active')),
                ('manager', models.ForeignKey(blank=True, help_text='The user responsible for managing this care home', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_homes', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Care Home',
                'verbose_name_plural': 'Care Homes',
                'ordering': ['name'],
            },
        ),
    ]
