# Generated by Django 5.0.6 on 2024-06-30 05:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_carehome_capacity_carehome_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carehome',
            options={'ordering': ['name'], 'verbose_name': 'Care Home', 'verbose_name_plural': 'Care Homes'},
        ),
        migrations.AddField(
            model_name='carehome',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the care home was added to the system', verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='carehome',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the care home information was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='carehome',
            name='address',
            field=models.TextField(help_text='The full address of the care home', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='carehome',
            name='capacity',
            field=models.PositiveIntegerField(default=100, help_text='Maximum number of residents the care home can accommodate', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='carehome',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='The user responsible for managing this care home', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_homes', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='carehome',
            name='name',
            field=models.CharField(help_text='The name of the care home', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='carehome',
            name='phone',
            field=models.CharField(help_text='Contact phone number for the care home', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone'),
        ),
    ]
