# Generated by Django 5.0.6 on 2024-06-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_alter_carehome_options_carehome_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carehome',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this care home is active.', verbose_name='Active'),
        ),
    ]
